// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function Calculate(arg1:string,arg2:backend.Settings):Promise<backend.CalculateResponse>;

export function LoadSettings():Promise<backend.Settings>;

export function SaveSettings(arg1:backend.Settings):Promise<void>;

export function SystemLocale():Promise<string>;

export function ValidateInput(arg1:string,arg2:backend.Settings):Promise<backend.ValidateResponse>;
