// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Calculate(arg1, arg2) {
  return window['go']['main']['App']['Calculate'](arg1, arg2);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SystemLocale() {
  return window['go']['main']['App']['SystemLocale']();
}

export function ValidateInput(arg1, arg2) {
  return window['go']['main']['App']['ValidateInput'](arg1, arg2);
}
